# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20170910_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='counter',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='song',
        ),
        migrations.AlterField(
            model_name='chat',
            name='lyric_tracker',
            field=models.ManyToManyField(through='database.Tracker', to='database.Song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='lines',
            field=models.IntegerField(blank=True),
        ),
        migrations.DeleteModel(
            name='Counter',
        ),
        migrations.AddField(
            model_name='tracker',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Chat'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Song'),
        ),
    ]
