# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20170910_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='players',
            field=models.ManyToManyField(blank=True, null=True, to='database.Player'),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.TextField(),
        ),
    ]
